# Generated by Django 5.2.6 on 2025-10-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="lesson",
        ),
        migrations.AddField(
            model_name="payment",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=50),
        ),
    ]
