# Generated by Django 5.2.6 on 2025-10-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_payment_course_remove_payment_lesson_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
    ]
