# Generated by Django 5.2.6 on 2025-10-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="object_id",
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счёт")],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
