# Generated by Django 5.2.6 on 2025-10-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_payment_content_type_remove_payment_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счeт")],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
