# Generated by Django 5.2.6 on 2025-09-28 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, unique=True, verbose_name="курс"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="lms/images"),
                ),
                (
                    "description",
                    models.TextField(max_length=200, verbose_name="описание"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, unique=True, verbose_name="урок"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="lms/images"),
                ),
                (
                    "description",
                    models.TextField(max_length=200, verbose_name="описание"),
                ),
                (
                    "video_link",
                    models.CharField(
                        blank=True, max_length=100, unique=True, verbose_name="ссылка"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lms.course",
                    ),
                ),
            ],
        ),
    ]
