# Generated by Django 5.2.6 on 2025-10-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["title"],
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["title"],
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
    ]
