# Generated by Django 5.2.6 on 2025-10-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="notification_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="id задачи уведомления",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления курса"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления урока"
            ),
        ),
    ]
